[workspace]
members = ["crates/spicetify", "crates/cli", "crates/tui", "crates/daemon"]
resolver = "2"

[workspace.package]
version = "0.0.9"
edition = "2024"
rust-version = "1.95"
repository = "https://github.com/veryboringhwl/app"
homepage = "https://spicetify.app"
authors = ["veryboringhwl"]
license = "MIT"
publish = false

[workspace.dependencies]
anyhow = "1.0"
thiserror = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "1.1"

tokio = { version = "1.52", features = [
  "rt",
  "rt-multi-thread",
  "net",
  "signal",
  "sync",
  "time",
  "macros",
] }
axum = { version = "0.8", features = ["ws", "macros"] }
reqwest = { version = "0.13", default-features = false, features = ["json", "rustls", "cookies"] }
futures-util = "0.3"

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

directories = "6.0"
notify = "9.0.0-rc.4"
fs4 = "1.1"
arc-swap = "1.9"
rustix = { version = "1.1", features = ["process"] }

url = "2.5"
percent-encoding = "2.3"
semver = "1.0"
regex-lite = "0.1"

zip = "8.6"
tar = "0.4"
zstd = "0.13"

i18n-embed = { version = "0.16", features = ["fluent-system", "desktop-requester"] }
i18n-embed-fl = "0.10"
rust-embed = { version = "8.11", features = ["interpolate-folder-path"] }

clap = { version = "4.6", features = ["derive", "wrap_help"] }

ratatui = "0.30"
crossterm = { version = "0.29", features = ["event-stream"] }

opener = "0.8"

color-eyre = "0.6"

windows = { version = "0.62", features = [
  "Win32_System_Threading",
  "Win32_System_Kernel",
  "Win32_Foundation",
  "Win32_Security",
] }
windows-registry = "0.6"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = true

[profile.dev]
debug = 0

[workspace.lints.rust]
unsafe_code = "deny"
unused_qualifications = "deny"
elided_lifetimes_in_paths = "deny"
missing_debug_implementations = "deny"
missing_copy_implementations = "deny"
noop_method_call = "deny"
unreachable_pub = "deny"
unused_crate_dependencies = "deny"
unused_extern_crates = "deny"
unused_results = "deny"
variant_size_differences = "deny"
non_ascii_idents = "deny"
unexpected_cfgs = { level = "allow" }
missing_docs = "allow"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }

dbg_macro = "deny"
todo = "deny"
unwrap_used = "deny"
panic = "deny"
redundant_clone = "deny"
disallowed_methods = "deny"

indexing_slicing = "warn"
struct_excessive_bools = "warn"

module_name_repetitions = "allow"
similar_names = "allow"
let_underscore_future = "allow"
single_range_in_vec_init = "allow"
must_use_candidate = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
