[package]
name = "cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
publish.workspace = true

[lints]
workspace = true

[[bin]]
name = "spicetify"
path = "src/main.rs"

[dependencies]
spicetify = { path = "../spicetify" }
tui = { path = "../tui" }
clap = { workspace = true, features = ["derive"] }
anyhow = { workspace = true }
i18n-embed-fl = { workspace = true }
