[package]
name = "cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
publish.workspace = true

[lints]
workspace = true

[[bin]]
name = "spicetify"
path = "src/main.rs"

[package.metadata.winresource]
FileDescription = "Spicetify"
ProductName = "Spicetify"

[dependencies]
spicetify = { path = "../spicetify" }
tui = { path = "../tui" }
clap = { workspace = true, features = ["derive"] }
anyhow = { workspace = true }
color-eyre = { workspace = true }
i18n-embed-fl = { workspace = true }

[target.'cfg(windows)'.build-dependencies]
winresource = "0.1"
