name: Release for windows
inputs:
   tag:
      description: Tag
      required: true
      type: string
   GH_TOKEN:
      description: GitHub token
      required: true
      type: string
runs:
   using: composite
   steps:
      -  name: Checkout
         uses: actions/checkout@v4

      -  name: Setup Go
         uses: actions/setup-go@v5
         with:
            go-version-file: "go.mod"

      -  name: Setup Wix
         shell: pwsh
         run: |
            dotnet tool install -g wix
            wix extension add -g WixToolset.Util.wixext
            wix extension add -g WixToolset.UI.wixext

      - run: mkdir dist

      -  name: Build
         shell: pwsh
         matrix:
            arch: [amd64, arm64, 386]
         run: |
            cd build\windows
            .\build.ps1 -version ${{ inputs.tag }} -platform ${{ matrix.arch }}
            mv spicetify.msi ..\..\dist\spicetify-${{ inputs.tag }}-${{ matrix.arch }}.msi

      -  name: Release
         uses: softprops/action-gh-release@v2
         with:
            files: "dist/*"
         env:
            GITHUB_TOKEN: ${{ inputs.GH_TOKEN }}
