name: Release for linux
inputs:
   tag:
      description: Tag
      required: true
      type: string
   GH_TOKEN:
      description: GitHub token
      required: true
      type: string
runs:
   using: composite
   steps:
      -  name: Checkout
         uses: actions/checkout@v4

      -  name: Setup Go
         uses: actions/setup-go@v5
         with:
            go-version-file: "go.mod"

      -  name: Build
         shell: bash
         run: |
            set -e
            cd build/linux
            ./build.sh ${{ inputs.tag }} amd64
            ./build.sh ${{ inputs.tag }} arm64
            mv spicetify ../../dist/spicetify-${{ inputs.tag }}-linux-${{ matrix.arch }}

      -  name: Release
         uses: softprops/action-gh-release@v2
         with:
            files: "dist/*"
         env:
            GITHUB_TOKEN: ${{ inputs.GH_TOKEN }}
