// Builds the client payload the Rust CLI stages into the patched client:
// the Spicetify wrapper and the modular loader, as classic non-deferred
// scripts. They are injected at the top of <body> so the wrapper runs before
// the client bundle (a module script would defer past webpack init), and the
// loader boots the client itself once mixins have run.
import { build } from "esbuild";
import { mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = process.cwd();
const outDir = resolve(root, process.argv[2] ?? "dist/hooks");

const targets = [
  {
    entry: resolve(root, "src/jsHelper/spicetifyWrapper/index.js"),
    out: resolve(outDir, "spicetifyWrapper.js"),
    // Literals that must survive minification, proving the bundle kept the
    // surface the client depends on.
    needles: ["Spicetify"],
  },
  {
    entry: resolve(root, "src/jsHelper/modularLoader/index.ts"),
    out: resolve(outDir, "modularLoader.js"),
    needles: ["spicetify.modules.local.", "[modular-loader]", "/modules/manifest.json", "/xpui-modules.js"],
  },
];

mkdirSync(outDir, { recursive: true });

for (const target of targets) {
  const result = await build({
    banner: { js: "/* Generated by scripts/build-payload.mjs. Do not edit directly. */" },
    bundle: true,
    entryPoints: [target.entry],
    format: "iife",
    legalComments: "none",
    logLevel: "silent",
    minify: true,
    outfile: target.out,
    sourcemap: true,
    sourcesContent: true,
    target: "chrome108",
    write: false,
  });

  const js = result.outputFiles.find((f) => f.path === target.out);
  for (const needle of target.needles) {
    if (!js.text.includes(needle)) {
      throw new Error(`${target.out} is missing ${needle} (check imports)`);
    }
  }
  for (const file of result.outputFiles) writeFileSync(file.path, file.contents);
  console.log(`built ${target.out}`);
}

writeFileSync(
  resolve(outDir, "payload.json"),
  `${JSON.stringify({ built: new Date().toISOString(), files: targets.map((t) => t.out.split("/").pop()) }, null, "\t")}\n`,
);
console.log(`payload ready at ${outDir}`);
