name: Build App (macOS)

on:
  workflow_call:
    inputs:
      tag:
        description: Version tag
        required: true
        type: string
      arch:
        description: Architecture
        required: true
        type: string

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Add Rust target
        run: rustup target add ${{ inputs.arch == 'x86_64' && 'x86_64-apple-darwin' || 'aarch64-apple-darwin' }}

      - name: Install build dependencies
        run: brew install create-dmg

      - name: Build
        working-directory: build/macos
        run: |
          chmod +x build.sh
          ./build.sh "${{ inputs.tag }}" "${{ inputs.arch }}"

      - name: Attest
        uses: actions/attest@v4
        with:
          subject-path: build/macos/dist/*

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: installer-macos-${{ inputs.arch }}
          path: build/macos/dist/*
