name: Build App (macOS)

on:
  workflow_call:
    inputs:
      tag:
        description: Version tag
        required: true
        type: string

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install build dependencies
        run: brew install create-dmg

      - name: Add Rust targets
        run: rustup target add x86_64-apple-darwin aarch64-apple-darwin

      - name: Build
        working-directory: build/macos
        run: |
          chmod +x build.sh
          ./build.sh "${{ inputs.tag }}"

      - name: Attest
        uses: actions/attest@v4
        with:
          subject-path: build/macos/dist/*

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: spicetify-macos
          path: build/macos/dist/*
