name: Code Quality
on:
  pull_request:
    branches: ["**"]
  push:
    branches: [main]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
      - name: Install nightly toolchain
        run: |
          rustup toolchain install nightly
          rustup component add rustfmt clippy --toolchain nightly
      - parallel:
          - name: Check formatting
            run: cargo +nightly fmt --check
          - name: Clippy
            run: cargo +nightly clippy --release --all-targets -- --deny warnings

  analyze:
    name: Analyze (${{ matrix.language }})
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - language: actions
          - language: rust
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: ${{ matrix.language }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4
        with:
          category: "/language:${{matrix.language}}"
