name: Commits linter

on: [pull_request]

jobs:
    commitlint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Lint commits
              uses: wagoid/commitlint-github-action@v5
